import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, json, boolean } from "drizzle-orm/mysql-core";

// ── Users ──
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── User Settings ──
export const userSettings = mysqlTable("user_settings", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  defaultMode: varchar("defaultMode", { length: 32 }).default("standard").notNull(),
  weatherCity: varchar("weatherCity", { length: 128 }).default("Seattle"),
  weatherLat: varchar("weatherLat", { length: 20 }),
  weatherLon: varchar("weatherLon", { length: 20 }),
  personalityTuning: json("personalityTuning"), // { formality, humor, depth }
  discoverInterests: json("discoverInterests"), // string[]
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type UserSettings = typeof userSettings.$inferSelect;

// ── Conversations ──
export const conversations = mysqlTable("conversations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull().default("New Conversation"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Conversation = typeof conversations.$inferSelect;

// ── Messages ──
export const messages = mysqlTable("messages", {
  id: int("id").autoincrement().primaryKey(),
  conversationId: int("conversationId").notNull(),
  role: mysqlEnum("role", ["user", "assistant", "system"]).notNull(),
  content: text("content").notNull(),
  toolCalls: json("toolCalls"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Message = typeof messages.$inferSelect;

// ── Memory (persistent knowledge) ──
export const memoryEntries = mysqlTable("memory_entries", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  category: varchar("category", { length: 64 }).notNull().default("general"),
  key: varchar("key", { length: 255 }).notNull(),
  value: text("value").notNull(),
  source: varchar("source", { length: 128 }).default("manual"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type MemoryEntry = typeof memoryEntries.$inferSelect;

// ── Network Events ──
export const networkEvents = mysqlTable("network_events", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  eventType: mysqlEnum("eventType", ["connection", "threat", "alert", "scan"]).notNull(),
  severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull().default("low"),
  sourceIp: varchar("sourceIp", { length: 45 }),
  destIp: varchar("destIp", { length: 45 }),
  port: int("port"),
  protocol: varchar("protocol", { length: 16 }),
  description: text("description").notNull(),
  metadata: json("metadata"),
  resolved: boolean("resolved").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type NetworkEvent = typeof networkEvents.$inferSelect;

// ── Analysis Results (EiRAM) ──
export const analysisResults = mysqlTable("analysis_results", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  inputText: text("inputText").notNull(),
  summary: text("summary"),
  moduleScores: json("moduleScores"),
  extractedFeatures: json("extractedFeatures"),
  riskVector: json("riskVector"),
  evidence: json("evidence"),
  forecast: text("forecast"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AnalysisResult = typeof analysisResults.$inferSelect;

// ── Plugins ──
export const plugins = mysqlTable("plugins", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 128 }).notNull(),
  description: text("description"),
  version: varchar("version", { length: 32 }).default("1.0.0"),
  code: text("code").notNull(),
  status: mysqlEnum("status", ["proposed", "active", "disabled", "failed"]).default("proposed").notNull(),
  autoGenerated: boolean("autoGenerated").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Plugin = typeof plugins.$inferSelect;

// ── Audit Log ──
export const auditLogs = mysqlTable("audit_logs", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  action: varchar("action", { length: 128 }).notNull(),
  category: mysqlEnum("category", ["chat", "network", "code", "engineering", "analysis", "memory", "plugin", "system", "discover", "news", "weather", "flights", "files", "settings", "instagram", "sentinel"]).notNull(),
  details: text("details"),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AuditLog = typeof auditLogs.$inferSelect;

// ── Code Executions ──
export const codeExecutions = mysqlTable("code_executions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  language: varchar("language", { length: 32 }).notNull(),
  code: text("code").notNull(),
  output: text("output"),
  error: text("error"),
  executionTimeMs: int("executionTimeMs"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type CodeExecution = typeof codeExecutions.$inferSelect;

// ── Instagram Cache ──
export const instagramCache = mysqlTable("instagram_cache", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  dataType: varchar("dataType", { length: 32 }).notNull(), // "account", "posts", "insights"
  data: json("data").notNull(),
  fetchedAt: timestamp("fetchedAt").defaultNow().notNull(),
});

export type InstagramCache = typeof instagramCache.$inferSelect;

// ── Sentinel Checks ──
export const sentinelChecks = mysqlTable("sentinel_checks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  category: mysqlEnum("category", ["system_health", "security", "performance", "inventory", "logs"]).notNull(),
  checkName: varchar("checkName", { length: 128 }).notNull(),
  scriptName: varchar("scriptName", { length: 128 }).notNull(),
  status: mysqlEnum("status", ["pass", "warning", "fail", "pending"]).default("pending").notNull(),
  output: text("output"),
  exitCode: int("exitCode"),
  executedAt: timestamp("executedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SentinelCheck = typeof sentinelChecks.$inferSelect;
