import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  ScrollText, MessageSquare, Shield, Code2, Wrench,
  Brain, Database, Puzzle, Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";

const moduleIcons: Record<string, typeof ScrollText> = {
  chat: MessageSquare,
  network: Shield,
  code: Code2,
  engineering: Wrench,
  analysis: Brain,
  memory: Database,
  plugin: Puzzle,
  system: Sparkles,
};

const moduleColors: Record<string, string> = {
  chat: "text-blue-400",
  network: "text-red-400",
  code: "text-green-400",
  engineering: "text-yellow-400",
  analysis: "text-purple-400",
  memory: "text-cyan-400",
  plugin: "text-orange-400",
  system: "text-primary",
};

export default function AuditPage() {
  const logsQuery = trpc.audit.logs.useQuery();
  const logs = logsQuery.data || [];

  return (
    <div className="h-full flex flex-col p-6 gap-6 overflow-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
          <ScrollText className="h-6 w-6 text-primary" />
          Audit Log
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Complete trail of all tool calls, decisions, and self-improvement actions taken by Seraphim.
        </p>
      </div>

      {/* Stats */}
      <div className="flex items-center gap-4 text-sm text-muted-foreground">
        <span>{logs.length} events recorded</span>
        {logs.length > 0 && (
          <span>
            Latest: {new Date(logs[0]?.createdAt || "").toLocaleString()}
          </span>
        )}
      </div>

      {/* Log List */}
      <Card className="flex-1 bg-card border-border">
        <CardContent className="p-0">
          <ScrollArea className="h-[calc(100vh-260px)]">
            {logs.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <ScrollText className="h-12 w-12 opacity-20 mb-3" />
                <p className="text-sm">No audit events yet. Actions will be logged as you use Seraphim.</p>
              </div>
            ) : (
              <div className="divide-y divide-border">
                {logs.map(log => {
                  const Icon = moduleIcons[log.category] || ScrollText;
                  const color = moduleColors[log.category] || "text-muted-foreground";
                  const meta = log.metadata ? (typeof log.metadata === "string" ? JSON.parse(log.metadata) : log.metadata) : null;
                  const isAutoGenerated = meta?.autoGenerated;

                  return (
                    <div key={log.id} className="flex items-start gap-4 px-6 py-3 hover:bg-accent/30 transition-colors">
                      <div className="mt-0.5">
                        <Icon className={cn("h-4 w-4", color)} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-sm font-medium text-foreground">{log.action}</span>
                          <Badge variant="outline" className={cn("text-xs", color, "border-current/20")}>
                            {log.category}
                          </Badge>
                          {isAutoGenerated && (
                            <Badge variant="outline" className="text-xs text-primary border-primary/30">
                              <Sparkles className="h-3 w-3 mr-1" /> Self-Improvement
                            </Badge>
                          )}
                        </div>
                        {log.details && (
                          <p className="text-xs text-muted-foreground truncate">{log.details}</p>
                        )}
                      </div>
                      <span className="text-xs text-muted-foreground shrink-0">
                        {new Date(log.createdAt).toLocaleString()}
                      </span>
                    </div>
                  );
                })}
              </div>
            )}
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  );
}
