import { trpc } from "@/lib/trpc";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  ScrollText, MessageSquare, Shield, Code2, Wrench,
  Brain, Database, Puzzle, Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";

const moduleIcons: Record<string, typeof ScrollText> = {
  chat: MessageSquare,
  network: Shield,
  code: Code2,
  engineering: Wrench,
  analysis: Brain,
  memory: Database,
  plugin: Puzzle,
  system: Sparkles,
};

const moduleColors: Record<string, string> = {
  chat: "text-blue-400",
  network: "text-red-400",
  code: "text-green-400",
  engineering: "text-amber-400",
  analysis: "text-purple-400",
  memory: "text-cyan-400",
  plugin: "text-orange-400",
  system: "text-primary",
};

const moduleBadge: Record<string, string> = {
  chat: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  network: "bg-red-500/10 text-red-400 border-red-500/20",
  code: "bg-green-500/10 text-green-400 border-green-500/20",
  engineering: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  analysis: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  memory: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
  plugin: "bg-orange-500/10 text-orange-400 border-orange-500/20",
  system: "bg-primary/10 text-primary border-primary/20",
};

export default function AuditPage() {
  const logsQuery = trpc.audit.logs.useQuery();
  const logs = logsQuery.data || [];

  return (
    <div className="h-full flex flex-col overflow-auto">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-border/50">
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center">
            <ScrollText className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-lg font-bold text-foreground">Audit Log</h1>
            <p className="text-[10px] font-bold uppercase tracking-[0.25em] text-muted-foreground/60">Activity Trail &middot; Transparency</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="nsa-card px-3 py-1.5 text-[11px] text-muted-foreground">
            <span className="text-primary font-semibold">{logs.length}</span> events
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-auto p-6">
        {/* Log Table */}
        <div className="nsa-card flex-1 flex flex-col overflow-hidden">
          <div className="px-4 py-3 border-b border-border/50 flex items-center justify-between">
            <p className="text-[10px] font-bold uppercase tracking-[0.25em] text-muted-foreground/60">Event Stream</p>
            {logs.length > 0 && (
              <p className="text-[11px] text-muted-foreground">
                Latest: {new Date(logs[0]?.createdAt || "").toLocaleString()}
              </p>
            )}
          </div>
          <ScrollArea className="flex-1 max-h-[calc(100vh-220px)]">
            {logs.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <ScrollText className="h-10 w-10 opacity-20 mb-3" />
                <p className="text-sm">No audit events yet. Actions will be logged as you use Seraphim.</p>
              </div>
            ) : (
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border/30">
                    <th className="text-left px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground w-8"></th>
                    <th className="text-left px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Action</th>
                    <th className="text-left px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Module</th>
                    <th className="text-left px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Details</th>
                    <th className="text-left px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Time</th>
                  </tr>
                </thead>
                <tbody>
                  {logs.map(log => {
                    const Icon = moduleIcons[log.category] || ScrollText;
                    const color = moduleColors[log.category] || "text-muted-foreground";
                    const badge = moduleBadge[log.category] || "bg-muted/10 text-muted-foreground border-border/30";
                    const meta = log.metadata ? (typeof log.metadata === "string" ? JSON.parse(log.metadata) : log.metadata) : null;
                    const isAutoGenerated = meta?.autoGenerated;

                    return (
                      <tr key={log.id} className="border-b border-border/20 hover:bg-white/[0.02] transition-colors">
                        <td className="px-4 py-2.5">
                          <Icon className={cn("h-3.5 w-3.5", color)} />
                        </td>
                        <td className="px-4 py-2.5">
                          <div className="flex items-center gap-2">
                            <span className="text-[13px] font-semibold text-foreground">{log.action}</span>
                            {isAutoGenerated && (
                              <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[9px] font-semibold bg-primary/10 text-primary border border-primary/20">
                                <Sparkles className="h-2 w-2" /> AUTO
                              </span>
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-2.5">
                          <span className={cn("inline-flex px-2 py-0.5 rounded-md text-[10px] font-semibold border", badge)}>
                            {log.category.toUpperCase()}
                          </span>
                        </td>
                        <td className="px-4 py-2.5 text-[12px] text-muted-foreground max-w-xs truncate">{log.details || "—"}</td>
                        <td className="px-4 py-2.5 text-[12px] text-muted-foreground/60 whitespace-nowrap">
                          {new Date(log.createdAt).toLocaleString()}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}
