export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  googleMapsTileApiKey: process.env.GOOGLE_MAPS_TILE_API_KEY ?? "",
  openSkyUsername: process.env.OPENSKY_USERNAME ?? "",
  openSkyPassword: process.env.OPENSKY_PASSWORD ?? "",
  celestrakBaseUrl: process.env.CELESTRAK_BASE_URL ?? "https://celestrak.org",
  enablePublicCameraLayer: process.env.ENABLE_PUBLIC_CAMERA_LAYER === "true",
};
