export type LabEntry = {
  id: string;
  title: string;
  category: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  objectives: string[];
  topology: string;
  keyCommands: string[];
  quizQuestions: { question: string; answer: string }[];
};

export const LAB_REGISTRY: LabEntry[] = [
  // ── Networking Fundamentals ──
  { id: "lab-01", title: "Basic Cable Connections & NIC Configuration", category: "Fundamentals", difficulty: "Beginner", objectives: ["Identify Ethernet cable types (straight-through, crossover, rollover)", "Configure a NIC with static IP", "Verify connectivity with ping"], topology: "2 PCs connected via Ethernet crossover cable", keyCommands: ["ipconfig", "ping", "ip addr show"], quizQuestions: [{ question: "When do you use a crossover cable?", answer: "When connecting two like devices (PC-to-PC, switch-to-switch) without auto-MDIX." }, { question: "What is the APIPA address range?", answer: "169.254.0.1 to 169.254.255.254 — assigned when DHCP fails." }] },
  { id: "lab-02", title: "TCP/IP Configuration & Troubleshooting", category: "Fundamentals", difficulty: "Beginner", objectives: ["Configure static IP addresses on multiple hosts", "Test connectivity across a subnet", "Use ipconfig, ping, and arp to diagnose issues"], topology: "3 PCs on a single switch, same subnet 192.168.1.0/24", keyCommands: ["ipconfig /all", "ping", "arp -a"], quizQuestions: [{ question: "What does a subnet mask of 255.255.255.0 mean?", answer: "The first 24 bits identify the network, last 8 bits identify hosts. Supports 254 usable hosts." }, { question: "Why might ping fail between two hosts on the same switch?", answer: "Wrong subnet mask, IP not in same subnet, Windows Firewall blocking ICMP, or cable issue." }] },
  { id: "lab-03", title: "OSI Model Layer Identification", category: "Fundamentals", difficulty: "Beginner", objectives: ["Map protocols and devices to OSI layers", "Identify encapsulation at each layer", "Understand PDU names (data, segment, packet, frame, bits)"], topology: "Conceptual — whiteboard exercise with packet capture analysis", keyCommands: ["tcpdump", "wireshark"], quizQuestions: [{ question: "At which OSI layer does a switch operate?", answer: "Layer 2 (Data Link) — it uses MAC addresses to forward frames." }, { question: "What is the PDU at Layer 3?", answer: "Packet — it contains source and destination IP addresses." }] },
  { id: "lab-04", title: "Binary & Decimal Conversion", category: "Fundamentals", difficulty: "Beginner", objectives: ["Convert between binary and decimal", "Understand how IP addresses are represented in binary", "Calculate network and broadcast addresses from binary"], topology: "Worksheet/calculator exercise", keyCommands: [], quizQuestions: [{ question: "Convert 192 to binary", answer: "11000000 (128+64=192)" }, { question: "What is 10101100 in decimal?", answer: "172 (128+32+8+4=172)" }] },

  // ── Subnetting & IP Addressing ──
  { id: "lab-05", title: "IPv4 Subnetting Practice", category: "Subnetting", difficulty: "Intermediate", objectives: ["Calculate subnet mask from CIDR notation", "Determine network address, broadcast address, and usable host range", "Subnet a Class C network into multiple subnets"], topology: "Paper exercise with verification on live network", keyCommands: ["ipconfig", "ip addr", "show ip interface brief"], quizQuestions: [{ question: "How many usable hosts in a /26 network?", answer: "62 hosts (2^6 - 2 = 62)" }, { question: "What is the network address for 192.168.1.130/26?", answer: "192.168.1.128 (third subnet: .0, .64, .128, .192)" }] },
  { id: "lab-06", title: "VLSM (Variable Length Subnet Masking)", category: "Subnetting", difficulty: "Advanced", objectives: ["Design an addressing scheme using VLSM", "Allocate different subnet sizes based on host requirements", "Minimize IP address waste"], topology: "Multi-site network: HQ (100 hosts), Branch1 (50 hosts), Branch2 (25 hosts), WAN links (2 hosts each)", keyCommands: ["show ip route", "ip route"], quizQuestions: [{ question: "Why use VLSM instead of fixed-length subnetting?", answer: "VLSM allows different subnet sizes, reducing IP address waste. Fixed subnetting wastes addresses when subnets have different host counts." }, { question: "What subnet mask gives exactly 2 usable hosts?", answer: "/30 (255.255.255.252) — used for point-to-point WAN links." }] },
  { id: "lab-07", title: "IPv6 Addressing & Configuration", category: "Subnetting", difficulty: "Intermediate", objectives: ["Configure IPv6 addresses on hosts and routers", "Understand link-local, global unicast, and multicast addresses", "Verify IPv6 connectivity with ping6"], topology: "2 routers connected via serial link, each with a LAN segment", keyCommands: ["ipv6 address", "show ipv6 interface brief", "ping6", "ip -6 addr show"], quizQuestions: [{ question: "What is the IPv6 link-local prefix?", answer: "fe80::/10 — automatically assigned, used for local segment communication only." }, { question: "How many bits in an IPv6 address?", answer: "128 bits (vs 32 bits in IPv4), written as 8 groups of 4 hex digits." }] },

  // ── Switching ──
  { id: "lab-08", title: "Basic Switch Configuration", category: "Switching", difficulty: "Beginner", objectives: ["Access switch CLI via console cable", "Set hostname, enable password, and banner", "Configure management VLAN IP for remote access"], topology: "1 switch, 1 PC connected via console cable", keyCommands: ["enable", "configure terminal", "hostname", "enable secret", "interface vlan 1", "ip address", "no shutdown", "copy run start"], quizQuestions: [{ question: "What is the difference between 'enable password' and 'enable secret'?", answer: "'enable secret' uses MD5 hashing and is more secure. 'enable password' stores in cleartext." }, { question: "Why configure an IP on VLAN 1?", answer: "For remote management via SSH/Telnet. The switch needs an IP to be reachable on the network." }] },
  { id: "lab-09", title: "VLAN Configuration & Trunking", category: "Switching", difficulty: "Intermediate", objectives: ["Create VLANs and assign ports", "Configure trunk links between switches", "Verify VLAN isolation and inter-VLAN traffic requirements"], topology: "2 switches connected via trunk, 4 PCs in 2 VLANs (Sales VLAN 10, Engineering VLAN 20)", keyCommands: ["vlan 10", "name Sales", "switchport mode access", "switchport access vlan 10", "switchport mode trunk", "show vlan brief", "show interfaces trunk"], quizQuestions: [{ question: "Can hosts in different VLANs communicate without a router?", answer: "No — VLANs create separate broadcast domains. A Layer 3 device (router or L3 switch) is needed for inter-VLAN routing." }, { question: "What protocol is used for VLAN trunking?", answer: "IEEE 802.1Q — inserts a 4-byte tag into the Ethernet frame identifying the VLAN." }] },
  { id: "lab-10", title: "Inter-VLAN Routing (Router-on-a-Stick)", category: "Switching", difficulty: "Intermediate", objectives: ["Configure subinterfaces on a router for each VLAN", "Set up 802.1Q encapsulation on subinterfaces", "Enable routing between VLANs"], topology: "1 router, 1 switch with trunk to router, 2 VLANs", keyCommands: ["interface g0/0.10", "encapsulation dot1Q 10", "ip address 192.168.10.1 255.255.255.0", "show ip route"], quizQuestions: [{ question: "What does 'router-on-a-stick' mean?", answer: "A single router interface divided into subinterfaces, each handling a different VLAN via 802.1Q trunking." }, { question: "What must the switch port connected to the router be configured as?", answer: "A trunk port — it must carry tagged traffic for all VLANs." }] },
  { id: "lab-11", title: "Spanning Tree Protocol (STP)", category: "Switching", difficulty: "Advanced", objectives: ["Understand STP root bridge election", "Identify root, designated, and blocked ports", "Configure STP priority to control root bridge selection"], topology: "3 switches in a triangle topology creating a loop", keyCommands: ["show spanning-tree", "spanning-tree vlan 1 priority 4096", "spanning-tree portfast"], quizQuestions: [{ question: "Why is STP necessary?", answer: "To prevent Layer 2 loops which cause broadcast storms, MAC table instability, and network outages." }, { question: "How is the root bridge elected?", answer: "The switch with the lowest Bridge ID (priority + MAC address) becomes root. Default priority is 32768." }] },
  { id: "lab-12", title: "EtherChannel Configuration", category: "Switching", difficulty: "Advanced", objectives: ["Bundle multiple physical links into one logical link", "Configure LACP (802.3ad) EtherChannel", "Verify load balancing across member links"], topology: "2 switches connected by 2 or more parallel links", keyCommands: ["interface range g0/1-2", "channel-group 1 mode active", "show etherchannel summary", "show etherchannel port-channel"], quizQuestions: [{ question: "What is the benefit of EtherChannel?", answer: "Increased bandwidth and redundancy without STP blocking redundant links." }, { question: "What is the difference between LACP and PAgP?", answer: "LACP is IEEE 802.3ad (open standard). PAgP is Cisco proprietary. LACP uses active/passive modes." }] },

  // ── Routing ──
  { id: "lab-13", title: "Static Routing Configuration", category: "Routing", difficulty: "Beginner", objectives: ["Configure static routes between routers", "Set up a default route for internet access", "Verify routing with show ip route and traceroute"], topology: "3 routers in a chain: R1 — R2 — R3, each with a LAN", keyCommands: ["ip route 10.0.0.0 255.0.0.0 192.168.1.2", "ip route 0.0.0.0 0.0.0.0 gateway", "show ip route", "traceroute"], quizQuestions: [{ question: "When is static routing appropriate?", answer: "Small networks, stub networks, default routes, or specific policy routes. Not scalable for large networks." }, { question: "What does a default route look like?", answer: "ip route 0.0.0.0 0.0.0.0 <next-hop> — matches any destination not in the routing table." }] },
  { id: "lab-14", title: "OSPF Single-Area Configuration", category: "Routing", difficulty: "Intermediate", objectives: ["Configure OSPF on multiple routers", "Verify neighbor adjacencies and LSDB", "Understand OSPF cost metric and path selection"], topology: "4 routers in Area 0 with redundant paths", keyCommands: ["router ospf 1", "network 192.168.1.0 0.0.0.255 area 0", "show ip ospf neighbor", "show ip ospf database", "show ip route ospf"], quizQuestions: [{ question: "What is the OSPF administrative distance?", answer: "110 — higher than static (1) and EIGRP (90), lower than RIP (120)." }, { question: "What is the OSPF wildcard mask for 255.255.255.0?", answer: "0.0.0.255 — the inverse of the subnet mask." }] },
  { id: "lab-15", title: "EIGRP Configuration", category: "Routing", difficulty: "Intermediate", objectives: ["Configure EIGRP on Cisco routers", "Understand DUAL algorithm and feasible successors", "Compare EIGRP with OSPF"], topology: "3 routers with EIGRP AS 100", keyCommands: ["router eigrp 100", "network 192.168.1.0", "show ip eigrp neighbors", "show ip eigrp topology", "show ip route eigrp"], quizQuestions: [{ question: "Is EIGRP a distance-vector or link-state protocol?", answer: "Advanced distance-vector (hybrid) — uses DUAL algorithm with some link-state characteristics." }, { question: "What is a feasible successor in EIGRP?", answer: "A backup route that meets the feasibility condition (reported distance < feasible distance of successor)." }] },
  { id: "lab-16", title: "NAT & PAT Configuration", category: "Routing", difficulty: "Intermediate", objectives: ["Configure static NAT for server access", "Configure dynamic NAT with a pool", "Configure PAT (overload) for internet access"], topology: "1 router connecting internal LAN (192.168.1.0/24) to simulated internet", keyCommands: ["ip nat inside source static 192.168.1.10 203.0.113.10", "ip nat inside source list 1 pool NATPOOL overload", "show ip nat translations", "show ip nat statistics"], quizQuestions: [{ question: "What is the difference between NAT and PAT?", answer: "NAT maps one private IP to one public IP. PAT (overload) maps many private IPs to one public IP using port numbers." }, { question: "Which interface is 'inside' and which is 'outside'?", answer: "Inside = private/LAN interface. Outside = public/WAN interface facing the internet." }] },

  // ── Security ──
  { id: "lab-17", title: "Access Control Lists (ACLs)", category: "Security", difficulty: "Intermediate", objectives: ["Create standard and extended ACLs", "Apply ACLs to interfaces (inbound/outbound)", "Test ACL filtering with ping and traceroute"], topology: "Router with 2 LANs — restrict traffic between them", keyCommands: ["access-list 101 permit tcp 192.168.1.0 0.0.0.255 host 10.0.0.10 eq 80", "access-list 101 deny ip any any", "ip access-group 101 in", "show access-lists"], quizQuestions: [{ question: "Where should you place a standard ACL?", answer: "Close to the destination — because standard ACLs only match source IP and you want to avoid blocking too broadly." }, { question: "Where should you place an extended ACL?", answer: "Close to the source — because extended ACLs can match source, destination, and port, allowing precise filtering." }] },
  { id: "lab-18", title: "SSH Configuration on Cisco Devices", category: "Security", difficulty: "Beginner", objectives: ["Generate RSA keys for SSH", "Configure VTY lines for SSH-only access", "Disable Telnet and verify secure remote access"], topology: "1 switch or router, 1 PC for SSH client", keyCommands: ["hostname Router1", "ip domain-name lab.local", "crypto key generate rsa modulus 2048", "line vty 0 4", "transport input ssh", "login local", "username admin secret P@ssw0rd"], quizQuestions: [{ question: "Why is SSH preferred over Telnet?", answer: "SSH encrypts all traffic including credentials. Telnet sends everything in cleartext." }, { question: "What is required before generating RSA keys?", answer: "A hostname and domain name must be configured first." }] },
  { id: "lab-19", title: "Port Security Configuration", category: "Security", difficulty: "Intermediate", objectives: ["Enable port security on switch access ports", "Set maximum MAC addresses per port", "Configure violation actions (shutdown, restrict, protect)"], topology: "1 switch, multiple PCs, attacker attempting MAC flooding", keyCommands: ["switchport port-security", "switchport port-security maximum 2", "switchport port-security violation shutdown", "switchport port-security mac-address sticky", "show port-security interface"], quizQuestions: [{ question: "What is a MAC flooding attack?", answer: "Attacker sends thousands of fake MAC addresses to overflow the switch CAM table, causing it to flood all traffic like a hub." }, { question: "What does 'sticky' MAC learning do?", answer: "Dynamically learns MAC addresses and adds them to the running config, persisting after save." }] },
  { id: "lab-20", title: "DHCP Snooping & Dynamic ARP Inspection", category: "Security", difficulty: "Advanced", objectives: ["Enable DHCP snooping to prevent rogue DHCP servers", "Configure trusted and untrusted ports", "Enable DAI to prevent ARP spoofing"], topology: "1 switch, 1 legitimate DHCP server, 1 rogue DHCP server, 2 clients", keyCommands: ["ip dhcp snooping", "ip dhcp snooping vlan 10", "ip dhcp snooping trust", "ip arp inspection vlan 10", "show ip dhcp snooping binding"], quizQuestions: [{ question: "What is a rogue DHCP server?", answer: "An unauthorized DHCP server that can assign wrong IPs/gateways, enabling man-in-the-middle attacks." }, { question: "Which ports should be trusted for DHCP snooping?", answer: "Only the port connected to the legitimate DHCP server and uplink/trunk ports." }] },

  // ── Services & Infrastructure ──
  { id: "lab-21", title: "DHCP Server Configuration", category: "Services", difficulty: "Beginner", objectives: ["Configure a Cisco router as a DHCP server", "Set pool, default gateway, DNS, and lease time", "Verify clients receive addresses automatically"], topology: "1 router as DHCP server, 1 switch, 3 PCs", keyCommands: ["ip dhcp pool LAN", "network 192.168.1.0 255.255.255.0", "default-router 192.168.1.1", "dns-server 8.8.8.8", "ip dhcp excluded-address 192.168.1.1 192.168.1.10", "show ip dhcp binding"], quizQuestions: [{ question: "What is the DORA process?", answer: "Discover → Offer → Request → Acknowledge — the 4-step DHCP lease process." }, { question: "Why exclude addresses from the pool?", answer: "To reserve IPs for servers, printers, and network devices that need static addresses." }] },
  { id: "lab-22", title: "DNS Configuration & Troubleshooting", category: "Services", difficulty: "Beginner", objectives: ["Configure DNS client settings on hosts and routers", "Perform forward and reverse DNS lookups", "Troubleshoot DNS resolution failures"], topology: "1 router, 1 DNS server, 2 clients", keyCommands: ["ip name-server 8.8.8.8", "ip domain-lookup", "nslookup", "dig", "Resolve-DnsName"], quizQuestions: [{ question: "What is the difference between an A record and a CNAME?", answer: "A record maps a hostname to an IP address. CNAME maps an alias to another hostname." }, { question: "What port does DNS use?", answer: "Port 53 — UDP for queries, TCP for zone transfers and large responses." }] },
  { id: "lab-23", title: "Syslog & NTP Configuration", category: "Services", difficulty: "Intermediate", objectives: ["Configure centralized syslog logging", "Set up NTP for time synchronization", "Correlate timestamps across devices for forensics"], topology: "2 routers, 1 syslog/NTP server", keyCommands: ["logging host 10.0.0.100", "logging trap informational", "ntp server 10.0.0.100", "show logging", "show ntp status", "show clock"], quizQuestions: [{ question: "Why is NTP important for security?", answer: "Accurate timestamps are critical for log correlation, forensic analysis, and certificate validation." }, { question: "What are the syslog severity levels?", answer: "0=Emergency, 1=Alert, 2=Critical, 3=Error, 4=Warning, 5=Notice, 6=Informational, 7=Debug" }] },

  // ── Wireless ──
  { id: "lab-24", title: "Wireless LAN Configuration", category: "Wireless", difficulty: "Intermediate", objectives: ["Configure SSID and security on a wireless access point", "Set up WPA2-PSK and WPA2-Enterprise", "Troubleshoot wireless connectivity issues"], topology: "1 wireless AP, 1 switch, 2 wireless clients", keyCommands: ["show dot11 associations", "show controllers dot11Radio0", "netsh wlan show profiles", "iwconfig"], quizQuestions: [{ question: "What is the difference between WPA2-PSK and WPA2-Enterprise?", answer: "PSK uses a shared password for all users. Enterprise uses 802.1X with individual credentials via a RADIUS server." }, { question: "What are the 2.4 GHz non-overlapping channels?", answer: "Channels 1, 6, and 11 — these don't interfere with each other." }] },

  // ── WAN & VPN ──
  { id: "lab-25", title: "GRE Tunnel Configuration", category: "WAN", difficulty: "Advanced", objectives: ["Configure a GRE tunnel between two routers", "Route traffic through the tunnel", "Understand GRE encapsulation overhead"], topology: "2 routers connected via simulated internet, GRE tunnel between LANs", keyCommands: ["interface tunnel 0", "tunnel source g0/0", "tunnel destination 203.0.113.2", "ip address 10.0.0.1 255.255.255.252", "show interface tunnel 0"], quizQuestions: [{ question: "What does GRE stand for and what does it do?", answer: "Generic Routing Encapsulation — encapsulates packets inside IP, creating a virtual point-to-point link over the internet." }, { question: "Does GRE provide encryption?", answer: "No — GRE only provides encapsulation. For encryption, combine with IPsec." }] },
  { id: "lab-26", title: "Site-to-Site VPN (IPsec)", category: "WAN", difficulty: "Advanced", objectives: ["Configure IKE Phase 1 and Phase 2 parameters", "Set up IPsec transform sets and crypto maps", "Verify VPN tunnel establishment"], topology: "2 routers simulating branch offices connected over the internet", keyCommands: ["crypto isakmp policy 10", "crypto ipsec transform-set MYSET esp-aes esp-sha-hmac", "crypto map MYMAP 10 ipsec-isakmp", "show crypto isakmp sa", "show crypto ipsec sa"], quizQuestions: [{ question: "What is the difference between IKE Phase 1 and Phase 2?", answer: "Phase 1 establishes a secure channel (ISAKMP SA) for negotiation. Phase 2 negotiates the actual IPsec SA for data encryption." }, { question: "What does ESP provide?", answer: "Encapsulating Security Payload provides confidentiality (encryption), integrity, and authentication." }] },

  // ── Troubleshooting ──
  { id: "lab-27", title: "Systematic Troubleshooting with OSI Model", category: "Troubleshooting", difficulty: "Intermediate", objectives: ["Apply bottom-up OSI troubleshooting methodology", "Check physical, data link, network, and transport layers systematically", "Document findings at each layer"], topology: "Broken network scenario with multiple faults planted", keyCommands: ["show ip interface brief", "show interfaces", "show vlan brief", "show ip route", "ping", "traceroute", "show access-lists"], quizQuestions: [{ question: "What is the bottom-up troubleshooting approach?", answer: "Start at Layer 1 (physical) and work up: cables → MAC/VLAN → IP/routing → ports/firewall → application." }, { question: "A host has IP 169.254.x.x — what layer is the problem?", answer: "Likely Layer 3 (DHCP not working) but could be Layer 1/2 (no connectivity to DHCP server)." }] },
  { id: "lab-28", title: "Packet Capture & Analysis with Wireshark", category: "Troubleshooting", difficulty: "Intermediate", objectives: ["Capture traffic with Wireshark or tcpdump", "Filter and analyze specific protocols", "Identify normal vs anomalous traffic patterns"], topology: "Switch with port mirroring to analysis PC", keyCommands: ["tcpdump -i eth0 -w capture.pcap", "wireshark", "tshark -r capture.pcap -Y 'tcp.port==80'"], quizQuestions: [{ question: "What is a TCP three-way handshake?", answer: "SYN → SYN-ACK → ACK — establishes a TCP connection between client and server." }, { question: "What does a RST packet indicate?", answer: "Connection reset — the destination is rejecting the connection (port closed, firewall, or application error)." }] },
];
