export type CommandEntry = {
  command: string;
  platform: "Windows" | "Linux" | "Cisco";
  category: string;
  purpose: string;
  syntax: string;
  goodOutput: string;
  badOutput: string;
  relatedPorts?: number[];
  tips: string;
};

export const COMMAND_LIBRARY: CommandEntry[] = [
  // ── Windows Commands ──
  { command: "ipconfig", platform: "Windows", category: "IP Configuration", purpose: "Display TCP/IP configuration for all adapters", syntax: "ipconfig [/all | /release | /renew | /flushdns | /displaydns]", goodOutput: "IPv4 Address: 192.168.1.10\nSubnet Mask: 255.255.255.0\nDefault Gateway: 192.168.1.1", badOutput: "Media disconnected\nAutoconfiguration IPv4 Address: 169.254.x.x (APIPA — no DHCP)", tips: "Use /all for full details including MAC, DHCP server, DNS. APIPA (169.254.x.x) means DHCP failed." },
  { command: "ping", platform: "Windows", category: "Connectivity", purpose: "Test reachability of a host using ICMP echo requests", syntax: "ping [-t] [-n count] [-l size] target", goodOutput: "Reply from 8.8.8.8: bytes=32 time=12ms TTL=118\nPackets: Sent=4, Received=4, Lost=0 (0% loss)", badOutput: "Request timed out.\nDestination host unreachable.\nGeneral failure.", tips: "Use -t for continuous ping. 'Request timed out' = host down or ICMP blocked. 'Destination unreachable' = routing issue." },
  { command: "tracert", platform: "Windows", category: "Routing", purpose: "Trace the route packets take to a destination, showing each hop", syntax: "tracert [-d] [-h max_hops] target", goodOutput: "1  <1ms  192.168.1.1\n2  5ms   10.0.0.1\n3  12ms  8.8.8.8", badOutput: "* * * Request timed out (hop blocking ICMP)\nUnable to resolve target system name", tips: "Use -d to skip DNS resolution for faster results. Asterisks (*) mean that hop blocks ICMP, not necessarily a failure." },
  { command: "nslookup", platform: "Windows", category: "DNS", purpose: "Query DNS servers for name resolution records", syntax: "nslookup [-type=A|MX|NS|CNAME|TXT] name [server]", goodOutput: "Name: www.example.com\nAddress: 93.184.216.34", badOutput: "*** Can't find server name for address\nDNS request timed out.\nNon-existent domain", relatedPorts: [53], tips: "Specify a server to test a specific DNS resolver. Use -type=MX for mail records, -type=NS for nameservers." },
  { command: "netstat", platform: "Windows", category: "Connections", purpose: "Display active connections, listening ports, and routing tables", syntax: "netstat [-a] [-n] [-o] [-b] [-r]", goodOutput: "TCP  0.0.0.0:80  0.0.0.0:0  LISTENING  4\nTCP  192.168.1.10:49152  93.184.216.34:443  ESTABLISHED", badOutput: "TIME_WAIT flood (connection exhaustion)\nCLOSE_WAIT accumulation (application not closing sockets)", tips: "Use -ano for all connections with PIDs. -b shows the executable. -r shows routing table. TIME_WAIT is normal but excessive counts indicate issues." },
  { command: "arp", platform: "Windows", category: "Layer 2", purpose: "Display and modify the ARP cache (IP-to-MAC mappings)", syntax: "arp [-a] [-d] [-s ip mac]", goodOutput: "192.168.1.1  00-1a-2b-3c-4d-5e  dynamic", badOutput: "No ARP Entries Found (interface down or no communication)\nDuplicate IP detected (ARP conflict)", tips: "Use arp -a to view cache. Duplicate MACs for different IPs may indicate ARP spoofing attack." },
  { command: "pathping", platform: "Windows", category: "Routing", purpose: "Combines ping and tracert with per-hop packet loss statistics", syntax: "pathping [-n] [-h max_hops] [-q num_queries] target", goodOutput: "Hop  RTT   Lost/Sent\n1    1ms   0/100 = 0%\n2    5ms   2/100 = 2%", badOutput: "100/100 = 100% loss at hop 3 (complete failure at that hop)", tips: "Takes 5+ minutes to complete. Best for identifying which specific hop is causing packet loss." },
  { command: "Test-NetConnection", platform: "Windows", category: "Connectivity", purpose: "PowerShell cmdlet for testing TCP connectivity to specific ports", syntax: "Test-NetConnection -ComputerName host -Port port [-InformationLevel Detailed]", goodOutput: "TcpTestSucceeded: True\nRemotePort: 443", badOutput: "TcpTestSucceeded: False\nWarning: TCP connect to (host:port) failed", relatedPorts: [80, 443, 3389], tips: "Modern replacement for telnet connectivity testing. Use -InformationLevel Detailed for full diagnostics." },
  { command: "route", platform: "Windows", category: "Routing", purpose: "Display and modify the local routing table", syntax: "route [print | add | delete] [destination] [mask] [gateway]", goodOutput: "Network Destination  Netmask        Gateway       Interface\n0.0.0.0            0.0.0.0        192.168.1.1   192.168.1.10", badOutput: "The route addition failed: Element not found (invalid gateway)\nNo matching route found", tips: "Use 'route print' to view. Default route is 0.0.0.0 with mask 0.0.0.0. Persistent routes survive reboots with -p flag." },
  { command: "netsh", platform: "Windows", category: "Configuration", purpose: "Network shell — configure interfaces, firewall, WLAN, and more", syntax: "netsh [interface | advfirewall | wlan] [subcommand]", goodOutput: "netsh interface ip show config\nDHCP enabled: Yes\nIP Address: 192.168.1.10", badOutput: "The following command was not found\nThe requested operation requires elevation", tips: "Use 'netsh wlan show profiles' for saved Wi-Fi. 'netsh advfirewall' for firewall rules. Requires admin elevation." },

  // ── Linux Commands ──
  { command: "ifconfig / ip addr", platform: "Linux", category: "IP Configuration", purpose: "Display or configure network interface parameters", syntax: "ip addr show [dev interface]\nifconfig [interface]", goodOutput: "inet 192.168.1.10/24 brd 192.168.1.255 scope global eth0\nlink/ether 00:1a:2b:3c:4d:5e", badOutput: "Device \"eth0\" does not exist\nSIOCSIFADDR: Permission denied", tips: "ifconfig is deprecated — use 'ip addr' on modern systems. 'ip link' shows layer 2 info. 'ip route' shows routing." },
  { command: "ss / netstat", platform: "Linux", category: "Connections", purpose: "Display socket statistics and active connections", syntax: "ss [-tlnp] [-a] [-s]\nnetstat [-tlnp]", goodOutput: "LISTEN  0  128  0.0.0.0:22  users:((\"sshd\",pid=1234))\nESTAB  0  0  192.168.1.10:22  10.0.0.5:49152", badOutput: "Cannot open netlink socket: Permission denied\nNo matching connections found", tips: "ss is faster than netstat. -t=TCP, -l=listening, -n=numeric, -p=process. Use -s for summary statistics." },
  { command: "dig", platform: "Linux", category: "DNS", purpose: "DNS lookup utility with detailed query/response information", syntax: "dig [@server] name [type] [+short | +trace]", goodOutput: "www.example.com.  300  IN  A  93.184.216.34\n;; Query time: 12 msec\n;; SERVER: 8.8.8.8#53", badOutput: "connection timed out; no servers could be reached\n;; status: NXDOMAIN (domain does not exist)", relatedPorts: [53], tips: "Use +short for just the answer. +trace follows the full resolution chain from root servers. @8.8.8.8 queries Google DNS." },
  { command: "tcpdump", platform: "Linux", category: "Packet Capture", purpose: "Capture and analyze network packets on an interface", syntax: "tcpdump [-i interface] [-n] [-c count] [filter expression]", goodOutput: "12:00:01 IP 192.168.1.10.49152 > 8.8.8.8.443: Flags [S], seq 12345\n12:00:01 IP 8.8.8.8.443 > 192.168.1.10.49152: Flags [S.], seq 67890, ack 12346", badOutput: "tcpdump: eth0: You don't have permission to capture\ntcpdump: No suitable device found", tips: "Requires root/sudo. Use -w file.pcap to save for Wireshark. Common filters: 'port 80', 'host 10.0.0.1', 'tcp and port 443'." },
  { command: "iptables / nftables", platform: "Linux", category: "Firewall", purpose: "Configure Linux kernel packet filtering and NAT rules", syntax: "iptables -L [-n] [-v]\niptables -A INPUT -p tcp --dport 22 -j ACCEPT", goodOutput: "Chain INPUT (policy DROP)\nACCEPT  tcp  --  0.0.0.0/0  0.0.0.0/0  tcp dpt:22", badOutput: "iptables: No chain/target/match by that name\niptables: Permission denied (must be root)", tips: "iptables is legacy — nftables is the modern replacement. Always set default policy last. Use -L -n -v for verbose numeric output." },
  { command: "curl", platform: "Linux", category: "HTTP", purpose: "Transfer data from or to a server using various protocols", syntax: "curl [-v] [-I] [-o output] [-X METHOD] [-H header] URL", goodOutput: "HTTP/1.1 200 OK\nContent-Type: text/html\n< Connection: keep-alive", badOutput: "curl: (7) Failed to connect to host port 443: Connection refused\ncurl: (6) Could not resolve host", relatedPorts: [80, 443], tips: "Use -v for verbose, -I for headers only, -k to skip TLS verification (testing only). Essential for API testing." },
  { command: "nmap", platform: "Linux", category: "Scanning", purpose: "Network exploration and security auditing — port scanner", syntax: "nmap [-sT|-sS|-sU] [-p ports] [-O] [-sV] target", goodOutput: "PORT    STATE  SERVICE\n22/tcp  open   ssh\n80/tcp  open   http\n443/tcp open   https", badOutput: "Note: Host seems down (ICMP blocked)\nAll 1000 scanned ports are filtered", tips: "Use -sS for SYN scan (stealthy, needs root). -sV for version detection. -O for OS detection. Only scan networks you own or have permission to scan." },
  { command: "traceroute", platform: "Linux", category: "Routing", purpose: "Trace the route to a host showing each network hop", syntax: "traceroute [-n] [-m max_hops] [-p port] target", goodOutput: "1  192.168.1.1  0.5ms\n2  10.0.0.1  5.2ms\n3  8.8.8.8  12.1ms", badOutput: "* * * (hop not responding)\ntraceroute: unknown host", tips: "Uses UDP by default (unlike Windows tracert which uses ICMP). Use -I for ICMP, -T for TCP. -n skips DNS resolution." },

  // ── Cisco IOS Commands ──
  { command: "show ip interface brief", platform: "Cisco", category: "IP Configuration", purpose: "Quick summary of all interfaces with IP addresses and status", syntax: "show ip interface brief", goodOutput: "GigabitEthernet0/0  192.168.1.1  YES manual  up  up\nGigabitEthernet0/1  10.0.0.1    YES DHCP    up  up", badOutput: "GigabitEthernet0/0  unassigned  YES unset  administratively down  down", tips: "First 'up' = Layer 1 (physical). Second 'up' = Layer 2 (protocol). 'administratively down' means shutdown command was used." },
  { command: "show running-config", platform: "Cisco", category: "Configuration", purpose: "Display the current active configuration in RAM", syntax: "show running-config [| section interface|router|line]", goodOutput: "hostname Router1\ninterface GigabitEthernet0/0\n ip address 192.168.1.1 255.255.255.0\n no shutdown", badOutput: "% Invalid input detected (wrong privilege level)\n% Unrecognized command", tips: "Use 'show run | section' to filter. Compare with 'show startup-config' to check unsaved changes. 'copy run start' to save." },
  { command: "show vlan brief", platform: "Cisco", category: "VLANs", purpose: "Display VLAN assignments and port membership on a switch", syntax: "show vlan brief", goodOutput: "VLAN  Name       Status  Ports\n1     default    active  Fa0/1, Fa0/2\n10    Sales      active  Fa0/3, Fa0/4\n20    Engineering active Fa0/5, Fa0/6", badOutput: "VLAN  Name    Status\n1     default active  (all ports in VLAN 1 — no segmentation configured)", tips: "All ports default to VLAN 1. Use 'switchport access vlan X' to assign ports. Trunk ports carry multiple VLANs." },
  { command: "show ip route", platform: "Cisco", category: "Routing", purpose: "Display the IP routing table with all known routes", syntax: "show ip route [static | connected | ospf | bgp]", goodOutput: "C  192.168.1.0/24 is directly connected, GigabitEthernet0/0\nS  10.0.0.0/8 [1/0] via 192.168.1.254\nO  172.16.0.0/16 [110/20] via 10.0.0.2", badOutput: "Gateway of last resort is not set (no default route)\n% Network not in table", tips: "C=Connected, S=Static, O=OSPF, D=EIGRP, B=BGP. [AD/metric] — lower AD is preferred. Default route: ip route 0.0.0.0 0.0.0.0 gateway." },
  { command: "show interfaces", platform: "Cisco", category: "Interface Details", purpose: "Detailed interface statistics including errors, CRC, and throughput", syntax: "show interfaces [interface-id]", goodOutput: "GigabitEthernet0/0 is up, line protocol is up\n  5 minute input rate 1000 bits/sec\n  0 input errors, 0 CRC", badOutput: "GigabitEthernet0/0 is up, line protocol is down (Layer 2 issue)\n  1234 input errors, 567 CRC, 89 frame", tips: "High CRC/input errors = cable or hardware issue. 'up/down' = L1 ok but L2 failed (encapsulation mismatch, no keepalives). Check duplex settings." },
  { command: "show mac address-table", platform: "Cisco", category: "Layer 2", purpose: "Display the MAC address table showing which MACs are on which ports", syntax: "show mac address-table [dynamic | static | address mac]", goodOutput: "VLAN  Mac Address      Type     Ports\n10    001a.2b3c.4d5e   DYNAMIC  Fa0/3\n20    00aa.bbcc.ddee   DYNAMIC  Fa0/5", badOutput: "Mac Address Table is empty (no traffic learned yet)", tips: "Dynamic entries are learned from traffic. Static entries are manually configured. Use for troubleshooting which device is on which port." },
  { command: "show spanning-tree", platform: "Cisco", category: "Layer 2", purpose: "Display Spanning Tree Protocol status to prevent Layer 2 loops", syntax: "show spanning-tree [vlan vlan-id] [detail]", goodOutput: "VLAN0010\n  Root ID  Priority 24586\n  Bridge ID Priority 32778\n  Interface  Role  Sts  Cost\n  Fa0/1      Root  FWD  19", badOutput: "Fa0/3  Altn  BLK  19 (port blocked — possible loop)\nMultiple root bridges detected (STP misconfiguration)", tips: "FWD=Forwarding, BLK=Blocking, LRN=Learning. Root bridge has lowest priority. Blocked ports prevent loops. Use 'spanning-tree portfast' on access ports." },
  { command: "show access-lists", platform: "Cisco", category: "Security", purpose: "Display configured ACLs and match counts", syntax: "show access-lists [number | name]", goodOutput: "Extended IP access list 101\n  10 permit tcp any host 192.168.1.10 eq 80 (1234 matches)\n  20 deny ip any any (5678 matches)", badOutput: "No ACLs configured\nImplicit deny all at end blocking legitimate traffic (0 permit matches)", tips: "ACLs process top-down, first match wins. Implicit 'deny any' at end. Apply with 'ip access-group' on interface. Standard ACLs: source only. Extended: source+dest+port." },
  { command: "show cdp neighbors", platform: "Cisco", category: "Discovery", purpose: "Display directly connected Cisco devices via CDP", syntax: "show cdp neighbors [detail]", goodOutput: "Device ID  Local Intrfce  Holdtme  Capability  Platform  Port ID\nSwitch2    Gig 0/1        178      S I         WS-C3750  Gig 0/1", badOutput: "CDP is not enabled (disabled for security)\n% CDP is not enabled on this interface", tips: "CDP is Cisco-proprietary. Use LLDP for multi-vendor. 'detail' shows IP addresses and IOS version. Disable on external-facing interfaces for security." },
  { command: "copy running-config startup-config", platform: "Cisco", category: "Configuration", purpose: "Save the running configuration to NVRAM so it persists after reboot", syntax: "copy running-config startup-config\nwrite memory (shortcut)", goodOutput: "[OK]\nBuilding configuration...", badOutput: "% Invalid input detected\n%Error opening nvram: (filesystem full)", tips: "CRITICAL: Changes are lost on reboot if not saved. 'wr' is the shortcut. 'copy start run' restores saved config. 'erase startup-config' for factory reset." },
];
